import React, { useState, useEffect } from 'react'
import Swal from 'sweetalert2'
import '../../styles/SuperCss/SuperTemplates.css'

const SuperTemplates = () => {
  const [templates, setTemplates] = useState([])
  const [selectedFormat, setSelectedFormat] = useState('pdf')
  const [selectedTemplate, setSelectedTemplate] = useState(null)
  const [isEditing, setIsEditing] = useState(false)
  const [templateName, setTemplateName] = useState('')
  const [elements, setElements] = useState([])
  const [draggedElement, setDraggedElement] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  // Available element types
  const elementTypes = [
    { type: 'logo', label: 'Logo', icon: '🖼️' },
    { type: 'title', label: 'Title', icon: '📝' },
    { type: 'subtitle', label: 'Subtitle', icon: '📄' },
    { type: 'text', label: 'Text', icon: '✏️' },
    { type: 'table', label: 'Table', icon: '📊' },
    { type: 'footer', label: 'Footer', icon: '📌' },
    { type: 'divider', label: 'Divider', icon: '➖' }
  ]

  useEffect(() => {
    fetchTemplates()
  }, [selectedFormat])

  const fetchTemplates = async () => {
    try {
      const response = await fetch(`/api/report-templates?format=${selectedFormat}`)
      if (response.ok) {
        const data = await response.json()
        setTemplates(data.templates || [])
      }
    } catch (err) {
      console.error('Error fetching templates:', err)
    }
  }

  const loadTemplate = (template) => {
    setSelectedTemplate(template)
    setTemplateName(template.name)
    setElements(template.elements || [])
    setIsEditing(true)
  }

  const createNewTemplate = () => {
    setSelectedTemplate(null)
    setTemplateName('')
    setElements([])
    setIsEditing(true)
  }

  const addElement = (elementType) => {
    const newElement = {
      id: Date.now().toString(),
      type: elementType,
      position: { x: 50, y: elements.length * 60 + 50 },
      size: { width: 200, height: 30 },
      content: elementType === 'title' ? 'Report Title' : 
               elementType === 'subtitle' ? 'Subtitle' : 
               elementType === 'text' ? 'Text content' : '',
      style: {
        fontSize: elementType === 'title' ? 20 : elementType === 'subtitle' ? 16 : 12,
        fontFamily: 'helvetica',
        fontStyle: elementType === 'title' ? 'bold' : 'normal',
        color: '#000000',
        alignment: 'left',
        backgroundColor: 'transparent'
      },
      tableConfig: elementType === 'table' ? {
        showHeaders: true,
        headerStyle: { fillColor: '#DC143C', textColor: '#FFFFFF' },
        rowStyle: { fillColor: '#F5F5F5', textColor: '#000000' }
      } : null
    }
    setElements([...elements, newElement])
  }

  const updateElement = (id, updates) => {
    setElements(elements.map(el => 
      el.id === id ? { ...el, ...updates } : el
    ))
  }

  const deleteElement = (id) => {
    setElements(elements.filter(el => el.id !== id))
  }

  const handleDragStart = (e, element) => {
    setDraggedElement(element)
    e.dataTransfer.effectAllowed = 'move'
  }

  const handleDragOver = (e) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = 'move'
  }

  const handleDrop = (e) => {
    e.preventDefault()
    if (!draggedElement) return

    const rect = e.currentTarget.getBoundingClientRect()
    const x = e.clientX - rect.left
    const y = e.clientY - rect.top

    updateElement(draggedElement.id, {
      position: { x, y }
    })
    setDraggedElement(null)
  }

  const saveTemplate = async () => {
    if (!templateName.trim()) {
      Swal.fire({
        title: 'Template Name Required',
        text: 'Please enter a template name before saving.',
        icon: 'warning',
        confirmButtonColor: '#dc143c'
      })
      return
    }

    setLoading(true)
    setError('')
    setSuccess('')

    try {
      const token = localStorage.getItem('superadmin_token')
      const storedUser = localStorage.getItem('superadmin_user')
      const userData = JSON.parse(storedUser)

      const templateData = {
        name: templateName,
        format: selectedFormat,
        elements: elements,
        isActive: true,
        pageSettings: {
          orientation: 'portrait',
          pageSize: 'a4',
          margins: { top: 20, bottom: 20, left: 20, right: 20 }
        },
        footerText: 'This is an official document generated by BSC Museum Management System',
        createdBy: userData.id
      }

      const url = selectedTemplate 
        ? `/api/report-templates/${selectedTemplate._id}`
        : '/api/report-templates'
      
      const method = selectedTemplate ? 'PUT' : 'POST'

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(templateData)
      })

      if (response.ok) {
        Swal.fire({
          title: 'Success!',
          text: selectedTemplate ? 'Template updated successfully!' : 'Template created successfully!',
          icon: 'success',
          confirmButtonColor: '#dc143c'
        })
        await fetchTemplates()
        setTimeout(() => {
          setIsEditing(false)
          setSuccess('')
        }, 1500)
      } else {
        const data = await response.json()
        Swal.fire({
          title: 'Save Failed',
          text: data.message || 'Failed to save template',
          icon: 'error',
          confirmButtonColor: '#dc143c'
        })
        setError(data.message || 'Failed to save template')
      }
    } catch (err) {
      Swal.fire({
        title: 'Network Error',
        text: 'Please check your connection and try again.',
        icon: 'error',
        confirmButtonColor: '#dc143c'
      })
      setError('Network error. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const deleteTemplate = async (templateId) => {
    const result = await Swal.fire({
      title: 'Delete Template?',
      text: 'This action cannot be undone. Are you sure you want to delete this template?',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#dc3545',
      cancelButtonColor: '#6c757d',
      confirmButtonText: 'Yes, delete it!',
      cancelButtonText: 'Cancel'
    })

    if (!result.isConfirmed) {
      return
    }

    try {
      const token = localStorage.getItem('superadmin_token')
      const response = await fetch(`/api/report-templates/${templateId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })

      if (response.ok) {
        Swal.fire({
          title: 'Deleted!',
          text: 'Template has been deleted successfully.',
          icon: 'success',
          confirmButtonColor: '#dc143c'
        })
        await fetchTemplates()
        if (selectedTemplate?._id === templateId) {
          setIsEditing(false)
          setSelectedTemplate(null)
        }
        setTimeout(() => setSuccess(''), 2000)
      } else {
        const data = await response.json()
        Swal.fire({
          title: 'Delete Failed',
          text: data.message || 'Failed to delete template',
          icon: 'error',
          confirmButtonColor: '#dc143c'
        })
        setError('Failed to delete template')
      }
    } catch (err) {
      Swal.fire({
        title: 'Network Error',
        text: 'Please check your connection and try again.',
        icon: 'error',
        confirmButtonColor: '#dc143c'
      })
      setError('Failed to delete template')
    }
  }

  return (
    <div className="dash-section">
      <div className="dash-header">
        <div>
          <h2 className="dash-title">Report Templates</h2>
          <p className="dash-subtitle">Design custom templates for PDF, Excel, and CSV exports</p>
        </div>
        {!isEditing && (
          <button className="create-template-btn" onClick={createNewTemplate}>
            + Create Template
          </button>
        )}
      </div>

      {error && <div className="error-message">{error}</div>}
      {success && <div className="success-message">{success}</div>}

      {!isEditing ? (
        <div className="templates-view">
          <div className="format-selector">
            <label>Select Format:</label>
            <select value={selectedFormat} onChange={(e) => setSelectedFormat(e.target.value)}>
              <option value="pdf">PDF</option>
              <option value="excel">Excel</option>
              <option value="csv">CSV</option>
            </select>
          </div>

          <div className="templates-list">
            {templates.length === 0 ? (
              <div className="empty-state">
                <p>No templates found for {selectedFormat.toUpperCase()}</p>
                <button onClick={createNewTemplate}>Create First Template</button>
              </div>
            ) : (
              templates.map(template => (
                <div key={template._id} className="template-card">
                  <div className="template-header">
                    <h3>{template.name}</h3>
                    <span className={`status-badge ${template.isActive ? 'active' : 'inactive'}`}>
                      {template.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </div>
                  <p className="template-format">{template.format.toUpperCase()}</p>
                  <p className="template-elements">{template.elements?.length || 0} elements</p>
                  <div className="template-actions">
                    <button onClick={() => loadTemplate(template)}>Edit</button>
                    <button onClick={() => deleteTemplate(template._id)} className="delete-btn">Delete</button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      ) : (
        <div className="template-editor">
          <div className="editor-header">
            <input
              type="text"
              placeholder="Template Name"
              value={templateName}
              onChange={(e) => setTemplateName(e.target.value)}
              className="template-name-input"
            />
            <div className="editor-actions">
              <button onClick={saveTemplate} disabled={loading} className="save-btn">
                {loading ? 'Saving...' : 'Save Template'}
              </button>
              <button onClick={() => {
                setIsEditing(false)
                setSelectedTemplate(null)
                setElements([])
              }} className="cancel-btn">
                Cancel
              </button>
            </div>
          </div>

          <div className="editor-content">
            <div className="elements-palette">
              <h3>Add Elements</h3>
              {elementTypes.map(elType => (
                <button
                  key={elType.type}
                  className="element-type-btn"
                  onClick={() => addElement(elType.type)}
                >
                  <span>{elType.icon}</span>
                  <span>{elType.label}</span>
                </button>
              ))}
            </div>

            <div 
              className="canvas-area"
              onDragOver={handleDragOver}
              onDrop={handleDrop}
            >
              <div className="canvas-header">
                <span>Design Canvas ({selectedFormat.toUpperCase()})</span>
                <span className="canvas-size">A4 Portrait</span>
              </div>
              {elements.map(element => (
                <div
                  key={element.id}
                  className="canvas-element"
                  style={{
                    left: `${element.position.x}px`,
                    top: `${element.position.y}px`,
                    width: `${element.size.width}px`,
                    height: `${element.size.height}px`,
                    fontSize: `${element.style.fontSize}px`,
                    color: element.style.color,
                    fontWeight: element.style.fontStyle === 'bold' ? 'bold' : 'normal',
                    fontStyle: element.style.fontStyle === 'italic' ? 'italic' : 'normal',
                    textAlign: element.style.alignment,
                    backgroundColor: element.style.backgroundColor
                  }}
                  draggable
                  onDragStart={(e) => handleDragStart(e, element)}
                >
                  {element.type === 'logo' && <span>🖼️ Logo</span>}
                  {element.type === 'table' && <span>📊 Table</span>}
                  {element.type === 'divider' && <hr />}
                  {['title', 'subtitle', 'text', 'footer'].includes(element.type) && (
                    <span>{element.content || element.type}</span>
                  )}
                  <button
                    className="element-delete-btn"
                    onClick={() => deleteElement(element.id)}
                  >
                    ×
                  </button>
                  <button
                    className="element-edit-btn"
                    onClick={() => {
                      const newContent = prompt('Enter content:', element.content)
                      if (newContent !== null) {
                        updateElement(element.id, { content: newContent })
                      }
                    }}
                  >
                    ✏️
                  </button>
                </div>
              ))}
            </div>

            <div className="properties-panel">
              <h3>Properties</h3>
              {elements.length === 0 ? (
                <p className="no-selection">Select an element to edit properties</p>
              ) : (
                <div className="properties-content">
                  <p>Select an element on the canvas to edit its properties</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default SuperTemplates

